package com.gvelesiani.common.constants

const val TABLE_NAME = "PASSWORD_TABLE"
const val MASTER_PASSWORD = "MASTER_PASSWORD"
const val PREVENT_TAKING_SCREENSHOTS = "TAKING_SCREENSHOTS_PREVENTED"
const val BIOMETRICS_ALLOWED = "BIOMETRICS_ALLOWED"
const val IS_INTRO_FINISHED = "IS_INTRO_FINISHED"
const val PASSWORDS_AS_STRING = "PASSWORDS_AS_STRING"
const val DATABASE_NAME = "PASSWORD_DATABASE"
const val PREFERENCES_KEY = "com.gvelesiani.passworx_preferences"